spring:
  application:
    name: "ScoreFlow"
  datasource:
    url: jdbc:postgresql://localhost:5432/scoring_db
    username: postgres
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

app:
  security:
    jwt: 4YmB3Nzc4WFl6QUJDREVGSElKS0xNTk9QUVJTVFVWV1hZWiEwMTIzNDU2Nzg5QGNoZXJlbmtvdg==